# Generated by extendr: Do not edit by hand
#
# This file was created with the following call:
#   .Call("wrap__make_helloextendr_wrappers", use_symbols = FALSE, package_name = "helloextendr")

#' Call Rust function `hello()`
#' 
#' Call Rust function `hello()`.
#' @export
hello <- function() .Call("wrap__hello", PACKAGE = "helloextendr")

